#AREA CIRCLE
"""def area_of_a_circle(pie,radius):
    area=pie*radius*radius
    print("area is",area)
area_of_a_circle (3.142,5)


#volume cylinder
def vol_of_a_cylinde(pie,radius,height):
    volume=pie*radius*radius*height
    print("volume is",volume)
vol_of_a_cylinde(3.142,5,7) 

#area pf a triangle 
def area_of_a_triangle(length,height):
    area=length*height
    print("area is",area)
area_of_a_triangle(4,6)   


#volume spere 
def vol_of_a_sphere(pie,radius):
    volume=pie*radius*radius*radius
    print("volume is",volume)
vol_of_a_sphere(3.142,15) """


#triangle area 
def area_of_a_triangle(base,half,height):
    area=base*height*half
    print("area is",area)
area_of_a_triangle(4,8,1/2)    
