# -*- coding: utf-8 -*-
"""Kebbs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PwIcHtit4G6w6RGt8dRmN3vM5gHa-9ae
"""

import pandas as pd
Data = pd.read_csv('kemmy.csv')
Data.head(30)



duplicates = Data[Data['Weather_Conditions'].duplicated()]
duplicates1 = Data[Data['Number_of_Casualties'].duplicated()]
print(duplicates)
print(duplicates1)

unique_values = Data.value_counts()
print(unique)

null = Data.isnull().sum()
print(null)



summary = Data.describe()
print(Data.info())
print(summary)

import matplotlib.pyplot as plt
variables = Data.loc[:,['Weather_Conditions','Number_of_Casualties']]
Data.plot(x='Weather_Conditions',y='Number_of_Casualties',style='*')
plt.xlabel('Weather_Conditions')
plt.ylabel('Number_of_Casualties')
plt.show()

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
X = Data[['Weather_Conditions']]
y = Data[['Number_of_Casualties']]
regressor.fit(X,y)
Data.plot(x='Weather_Conditions',y='Number_of_Casualties',style='*')
plt.plot(X, regressor.predict(X), color='red', label='Regression line')
plt.xlabel('Weather_Conditions')
plt.ylabel('Number_of_Casualties')
plt.show()

x = pd.DataFrame(Data['Weather_Conditions'])
y = pd.DataFrame(Data['Number_of_Casualties'])
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=1)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)
regressor = LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.intercept_)
print(regressor.coef_)
y_pred = regressor.predict(x_test)
# print(y_pred)
y_test

#Evaluation
from sklearn import metrics
import numpy as np
mae = metrics.mean_absolute_error(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print("MAE", mae)
print("MSE", mse)
print("RMSE", rmse)

#Save the model
import joblib
import pickle
#train the model
model = LinearRegression()
model.fit(x,y)
joblib.dump(model, 'kemmy.pkl')
with open('kemmy.pkl', 'wb') as file:
  pickle.dump(model, file)

new_x = np.array([10,20,30,40,50]).reshape(-1,1)
model = joblib.load('kemmy.pkl')
predictions = model.predict(new_x)
new_data=pd.DataFrame({'x':new_x.flatten(), 'Predicted_y': predictions.flatten()})
print(new_data)

